# Autogenerated from /home/powerai/triton/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.triton_obj_root = "/home/powerai/triton"
config.llvm_src_root = ""
config.llvm_obj_root = "/usr/local"
config.llvm_tools_dir = "/usr/local/bin"
config.llvm_lib_dir = "/usr/local/lib"
config.llvm_shlib_dir = "/home/powerai/triton/python/triton/_C"
config.llvm_shlib_ext = ".so"
config.llvm_exe_ext = ""
config.lit_tools_dir = ""
config.mlir_binary_dir = ""
config.python_executable = "/usr/bin/python3"
config.enable_bindings_python = 0
config.build_shared_libs = 0


import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work
lit_config.load_config(config, "/home/powerai/triton/test/lit.cfg.py")
