if(NOT DEFINED JSON_INCLUDE_DIR OR "${JSON_INCLUDE_DIR}" STREQUAL "")
  set(JSON_INCLUDE_DIR "/home/powerai/build-triton/.nlohmann-prefix/include")
endif()
if(NOT DEFINED JSON_SYSPATH OR "${JSON_SYSPATH}" STREQUAL "")
  set(JSON_SYSPATH "/home/powerai/build-triton/.nlohmann-prefix")
endif()
if(NOT DEFINED LLVM_INCLUDE_DIRS OR "${LLVM_INCLUDE_DIRS}" STREQUAL "")
  set(LLVM_INCLUDE_DIRS "/usr/local/include")
endif()
if(NOT DEFINED LLVM_LIBRARY_DIR OR "${LLVM_LIBRARY_DIR}" STREQUAL "")
  set(LLVM_LIBRARY_DIR "/usr/local/lib")
endif()
if(NOT DEFINED LLVM_SYSPATH OR "${LLVM_SYSPATH}" STREQUAL "")
  set(LLVM_SYSPATH "/usr/local")
endif()
